type = "csharp"
main = "server/tr-world.dll"
deps = [
    'chat'
]
client-type = "csharp"
client-main = "client/Release/win-x64/trWorld_client.dll"
client-files = [
    "client/Release/win-x64/trWorld_client.dll",
    "client/Release/win-x64/AltV.Net.dll",
    "client/Release/win-x64/AltV.Net.Client.dll",
    "client/Release/win-x64/AltV.Net.Shared.dll",
    "client/Release/win-x64/AltV.Net.CApi.dll"
]